version: '3'

services:
   php-redirect-site:
     container_name: ${CONATINER_NAME}
     image: php:7.2.9-apache
     restart: unless-stopped
     volumes:
       - ${PHP_HOME:-./../data/}:/var/www/html
     environment:
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}
